---
title: "variogram / triangle demo"
author: "EW"
date: "11/6/2021"
output: pdf_document
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(inlabru)
library(INLA)
library(dplyr)
# library(fmesher)
# https://www.maths.ed.ac.uk/~flindgre/2018/07/22/spatially-varying-mesh-quality/

haul <- readRDS("data/haul_cleaned.rds")
catch <- readRDS("data/catch_cleaned.rds")

# species are dover sole, sablefish, petrale sole, lingcod, darkblotched rockfish
# g = group_by(catch, common_name) %>% dplyr::summarise(p = sum(present)) %>% dplyr::arrange(-p)
catch_sub <- dplyr::filter(catch, common_name == "Dover sole")
# Join catch and haul data
haul_new <- haul %>%
    left_join(catch_sub, by = "trawl_id") %>%
    select(trawl_id, X, Y,
      latitude = latitude_dd.x,
      longitude = longitude_dd.x,
      year = year,
      log_depth_scaled,
      log_depth_scaled2,
      cpue_kg_km2
    )
  # Set NA CPUEs to 0
  haul_new$cpue_kg_km2[which(is.na(haul_new$cpue_kg_km2))] <- 0

  # convert coordinates to km
  haul_new$X <- haul_new$X / 1000
  haul_new$Y <- haul_new$Y / 1000

  
```


We can fit the variogram in `gstat`, 

```{r}
library(gstat)
# fit a logistic regression
haul_new$present = ifelse(haul_new$cpue_kg_km2>0,1,0)
g <- glm(present ~ 1, data=haul_new, family="binomial")
haul_new$pearson = residuals(g,type="pearson")
# variogram
vg1 <- variogram(pearson ~ 1, locations = ~ X+Y, data=haul_new,
                 cressie=TRUE)
plot(vg1)
```

We could do the same thing for the postivie model
```{r}
haul_new = dplyr::filter(haul_new, cpue_kg_km2>0)
g <- glm(cpue_kg_km2 ~ 1, data=haul_new, family="Gamma")
haul_new$pearson = residuals(g,type="pearson")
# variogram
vg2 <- variogram(pearson ~ 1, locations = ~ X+Y, data=haul_new,
                 cressie=TRUE)
plot(vg2)
```

